service: 'datadog-forward'

provider:
  name: aws
  stage: 'develop'
  region: 'us-east-1'
  deploymentBucket:
    serverSideEncryption: AES256
    blockPublicAccess: true
    name: serverless-datadog-develop
  tags:
    owner: i
    createdby: serverless

plugins:
  modules:
    - ./index.js
    - serverless-deployment-bucket

custom:
  bucket: my-existent-bucket-logs


  datadogLogForward:
    apiKey: '' # from env
    functionName: team-datadoglogforward-${self:provider.stage}
    bucket: ${self:custom.bucket}
    extendsFn:
      memorySize: 256
